CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL DEFAULT 0,
    source WORD NOT NULL,
    target WORD NOT NULL,
    reason WORD,
    amount INTEGER NOT NULL
);
